change baseUrl, remove the need to add automl baseUrl in gladia clien…
gladiaio/gladia-sdk-js pull request #12
Opened 2022-12-06 11:27 UTC by amorin-gladia

…t and filter automl endpoints in the file_to_file task generation

2022-12-06 13:03 UTC, jsoto-gladia approved these changes
a mon avis tu dois merge celle ci en premier
prendre la nouvelle version 
update la version du sdk dans office-addin

2022-12-06 16:27 UTC, kuroidoruido requested changes

2022-12-06 16:27 UTC, kuroidoruido commented on src/client/automl/AutoMLTrainable.ts
> -    if (!isPreviewEnabled(this.params) || isNotDefined(this.params.autoMlBaseUrl)) {
as you remove this `isNotDefined` call the import on top of the file is now useless

2022-12-07 08:12 UTC, jsoto-gladia commented
@amorin-gladia can you merge this today ?

2022-12-09 11:28 UTC, kuroidoruido approved these changes

2022-12-09 11:29 UTC, merged